// <auto-generated />
namespace IMDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddActors7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddActors7));
        
        string IMigrationMetadata.Id
        {
            get { return "201412191006134_AddActors7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
